name: flutter_dapm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  carousel_slider_plus: 7.1.1 
  intl: ^0.18.1
  get_storage: ^2.1.1 
  google_sign_in: ^6.2.1
  dio: ^5.8.0+1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
#  google_maps_flutter: ^2.6.1 # Gói để hiển thị bản đồ
#  google_maps_apis: ^3.0.1
  flutter_map: ^6.1.0 # Để hiển thị bản đồ OSM
  latlong2: ^0.9.0    # Cung cấp đối tượng LatLng cho flutter_map

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_splash.png
    - assets/burger.png
    - assets/pizza.png
    - assets/burrito.png
    - assets/drink.png
    - assets/burger_2gagion.jpg
    - assets/burger_gagion.jpg
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets/google_logo.png
    - assets/momo_logo.png
    - assets/vnpay_logo.png
    - assets/bank.png

