name: flutter_dapm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  carousel_slider_plus: 7.1.1 
  intl: ^0.18.1
  get_storage: ^2.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_splash.png
    - assets/burger.png
    - assets/pizza.png
    - assets/burrito.png
    - assets/drink.png
    - assets/burger_2gagion.jpg
    - assets/burger_gagion.jpg
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
